In [2]:
import numpy as np
import sklearn as skl
from sklearn.linear_model import Perceptron

In [5]:
input_array=np.array([
    [0,0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,1,0],
    [0,0,0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,1,0,0,0],
    [0,0,0,0,0,1,0,0,0,0],
    [0,0,0,0,1,0,0,0,0,0],
    [0,0,0,1,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0,0,0],
    [0,1,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,0],
])

label=np.array([1,-1,1,-1,1,-1,1,-1,1,-1])
perceptron=Perceptron(max_iter=100,tol=None)
perceptron.fit(input_array,label)
Perceptron(max_iter=100,tol=None)

for i in input_array:
    pr=perceptron.predict([i])
    if pr==1:
        print(i,"EVEN")
    else:
        print(i,"ODD")

[0 0 0 0 0 0 0 0 0 1] EVEN
[0 0 0 0 0 0 0 0 1 0] ODD
[0 0 0 0 0 0 0 1 0 0] EVEN
[0 0 0 0 0 0 1 0 0 0] ODD
[0 0 0 0 0 1 0 0 0 0] EVEN
[0 0 0 0 1 0 0 0 0 0] ODD
[0 0 0 1 0 0 0 0 0 0] EVEN
[0 0 1 0 0 0 0 0 0 0] ODD
[0 1 0 0 0 0 0 0 0 0] EVEN
[1 0 0 0 0 0 0 0 0 0] ODD
